server:
  port: 8080

spring:
  application:
    name: be

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret-key: ${jwt-secret-key}
#  expired-time-ms: ${jwt-expired-time-ms}
  access-token:
    plus-hour: ${jwt-access-token-plus-hour}
  refresh-token:
    plus-hour: ${jwt-refresh-token-plus-hour}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO