server:
  port: 8080

spring:
  application:
    name: be

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret-key: ${jwt-secret-key}
  access-token:
    plus-hour: ${jwt-access-token-plus-hour}
  refresh-token:
    plus-hour: ${jwt-refresh-token-plus-hour}

cloud:
  aws:
    s3:
      bucket: ${s3-bucket}

    credentials:
      access-key: ${s3-access-key}
      secret-key: ${s3-secret-key}

    region:
      static: ${s3-region-static}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO

servers:
  url: "http://localhost"
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
