server:
  port: ${server-port}

management:
  server:
    port: ${management-server-port}

spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
  data:
    redis:
      host: ${redis-host}
      port: ${redis-port}

jwt:
  secret-key: ${jwt-secret-key}
  access-token:
    plus-hour: ${jwt-access-token-plus-hour}
  refresh-token:
    plus-hour: ${jwt-refresh-token-plus-hour}

servers:
  url: ${servers-url}

## s3 이미지 저장
cloud:
  aws:
    s3:
      bucket: ${s3-bucket}

    credentials:
      access-key: ${s3-access-key}
      secret-key: ${s3-secret-key}

    region:
      static: ${s3-region-static}